---
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  # If you need to share「requirements.txt」with multiple Lambda functions,
  # you need to use「LayerVersion」and specify it with「ContentUri」. However,
  # if you are incorporating it into a Lambda function,
  # you can simply store「requirements.txt」in the directory specified by「CodeUri」.
  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: python3.12
      BuildArchitecture: x86_64
    Properties:
      LayerName: MyLayer
      Description: Layer description
      ContentUri: ./lambda_layer
      CompatibleRuntimes:
        - python3.12
      CompatibleArchitectures:
        - x86_64
      RetentionPolicy: Delete

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloWorldFunction
      Handler: Hello.lambda_handler
      Runtime: python3.12
      Timeout: 60
      CodeUri: app_dir/
      Layers:
        - !Ref LambdaLayer
      Environment:
        Variables:
          LOG_LEVEL: "INFO"
      # DeploymentPreference:
      #     Type: Linear10PercentEvery1Minute