---
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  StepFunctionsName:
    Type: String
    Default: 'teststepfunctions'

  CloudWatchLogsName:
    Type: String
    Default: 'StepFunctionsLog'

  IAMRoleName:
    Type: String
    Default: 'StepFunctionsIAMRole'

Resources:
  StepFunctions:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Ref StepFunctionsName
      DefinitionUri: ./app_dir/StepFunctionsDefinition.json
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt ClousWatchLogs.Arn
        Level: "ERROR"
      Role: !GetAtt IAMRole.Arn
      Type: "STANDARD"

  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref IAMRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - states.amazonaws.com
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'

  ClousWatchLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref CloudWatchLogsName
      LogGroupClass: 'INFREQUENT_ACCESS'
      RetentionInDays: 1